const P={name:"Lingesh S",headline:"CSE-AIML Student → Future AI Engineer",intro:"Exploring AI to build intelligent solutions for real-world problems.",location:"Tiruchirappalli, Tamil Nadu",email:"lingesh130208@gmail.com",github:"https://github.com/lingesh-130208",leetcode:"https://leetcode.com/u/lingesh_13",portfolio:"https://github.com/lingesh-130208/lingesh-portfolio-"};

const projects=[
{slug:"smartpillcare",title:"SmartPillCare 2.0",area:"AI + Healthcare + Robotics",icon:"💊",desc:"A smart healthcare concept focused on medication adherence for elderly and chronic-care patients.",tags:["Healthcare AI","Automation","Medication Adherence"],repo:"https://github.com/lingesh-130208/lingesh-portfolio-/tree/main/projects/SmartPillCare-2.0",status:"Concept / project development",points:["Scheduled medicine dispensing","Prescription verification","Time-locked dispensing","Usage logging and alerts","Caregiver / medical monitoring","Emergency assistance"],event:"Nimirthu Nill TN Hackathon — Participant"},
{slug:"gridlock",title:"Gridlock Prevention 2.0",area:"AI + Smart Cities",icon:"🚦",desc:"An intelligent traffic-management concept using traffic-density analysis, adaptive signal control and emergency-vehicle prioritization.",tags:["Smart Cities","Traffic AI","Adaptive Signals"],repo:"https://github.com/lingesh-130208/lingesh-portfolio-/tree/main/projects/GridlockZero",status:"Concept / presentation project",points:["Traffic-density analysis","Adaptive signal decisions","Emergency vehicle prioritization","Reduced waiting-time objective","Smart-city mobility focus"],event:"STRATA'26 — National Level Technical Symposium · Paper Presentation"},
{slug:"erp",title:"College ERP System",area:"Web Application",icon:"🎓",desc:"A browser-based college-management system covering students, faculty, courses, attendance and results.",tags:["HTML","CSS","JavaScript","LocalStorage"],repo:"https://github.com/lingesh-130208/lingesh-portfolio-/tree/main/projects/College-ERP-System",status:"Working demo",points:["Dashboard summaries","Student records","Faculty records","Course management","Attendance view","Results view"],event:"Independent portfolio project"},
{slug:"practice",title:"Java & C++ Practice",area:"Programming + DSA",icon:"💻",desc:"An ongoing practice collection for programming fundamentals, OOP, data structures, algorithms and LeetCode-style problem solving.",tags:["Java","C++","DSA","LeetCode"],repo:"https://github.com/lingesh-130208/lingesh-portfolio-/tree/main/projects/Java-Cpp-Practice",status:"Ongoing",points:["Java and C++ practice","Object-oriented programming","Stacks, queues and linked lists","Trees and algorithms","LeetCode-style problems"],event:"Ongoing learning"}
];

const skills=[
["Programming",["Java","C++"]],["Web",["HTML","CSS","JavaScript"]],["AI / Tools",["Prompt Engineering","Generative AI"]],["Core Strengths",["Problem Solving","Debugging","Logical Thinking"]],["Platforms",["GitHub","LeetCode"]],["Focus Areas",["AI + Healthcare","AI + Smart Cities","AI + Robotics"]]
];

const timeline=[
["2026","Paper Presentation","STRATA'26 — National Level Technical Symposium","Paper Presentation — Gridlock Prevention"],
["11 Feb 2026","Presentation","National Mathematics Day — SRM TRP Engineering College","Certificate of Appreciation for an exceptional presentation on Traffic Management for Gridlock."],
["2026","Hackathon","Nimirthu Nill TN Hackathon","Participant — SmartPillCare"]
];

const credentials=[
["STRATA'26 — Paper Presentation","Loyola-ICAM College of Engineering and Technology","2026","National-level technical symposium presentation.",""],
["Certificate of Appreciation — Traffic Management for Gridlock","SRM TRP Engineering College · National Mathematics Day","2026","Recognition for an exceptional presentation.",""],
["Nimirthu Nill TN Hackathon","Hackathon participation","2026","Participant with SmartPillCare.",""]
];

const $=x=>document.querySelector(x);
function header(){return `<header class="nav"><div class="container nav-inner"><a class="brand" href="#home"><span class="mark">LS</span><span><b>LINGESH S</b><small>CSE-AIML · Future AI Engineer</small></span></a><button class="menu" id="menu">☰</button><nav class="links" id="links"><a href="#home">Home</a><a href="#about">About</a><a href="#skills">Skills</a><a href="#projects">Projects</a><a href="#journey">Journey</a><a href="#credentials">Credentials</a><a class="gh" href="${P.github}" target="_blank">GitHub ↗</a></nav></div></header>`}
function footer(){return `<footer class="footer"><div class="container footer-row"><div><div class="brand"><span class="mark">LS</span><b>LINGESH S</b></div><p style="color:#667991;font-size:11px">CSE-AIML Student → Future AI Engineer.</p></div><div class="footer-links"><a href="${P.github}" target="_blank">GitHub</a><a href="${P.leetcode}" target="_blank">LeetCode</a><a href="mailto:${P.email}">Email</a></div></div><div class="container bottom"><span>© 2026 Lingesh S</span><span>Built for learning, building and competing.</span></div></footer>`}
function card(p,i){return `<article class="card reveal"><div class="art"><span class="icon">${p.icon}</span><span class="num">0${i+1}</span></div><div class="card-body"><span class="eyebrow">${p.area}</span><h3>${p.title}</h3><p>${p.desc}</p><div class="tags">${p.tags.map(t=>`<span class="tag">${t}</span>`).join("")}</div><div class="card-actions"><a class="link" href="#project/${p.slug}">Explore ↗</a><a class="link" href="${p.repo}" target="_blank">GitHub ↗</a></div></div></article>`}
function home(){return `${header()}<main>
<section class="hero" id="home"><div class="container hero-grid"><div><span class="status"><i class="pulse"></i> Open to learning · building · competing</span><h1>${P.name}<span>${P.headline}</span></h1><p class="lead">${P.intro}</p><div class="actions"><a class="btn primary" href="#projects">Explore projects ↗</a><a class="btn secondary" href="${P.github}" target="_blank">GitHub ↗</a><a class="btn secondary" href="assets/resume.pdf" target="_blank">Resume ↗</a></div><div class="meta"><span>⌖ ${P.location}</span><span>✉ ${P.email}</span></div></div><div class="visual"><div class="orb"></div><div class="ring"></div><img class="photo" src="assets/profile.jpg" alt="Lingesh S"><div class="float f1">⚡ Generative AI</div><div class="float f2">🏆 Hackathon Builder</div><div class="float f3">🧠 Problem Solver</div></div></div></section>
<section class="section" id="about"><div class="container split"><div class="heading reveal"><span class="eyebrow">01 · About</span><h2>Learning AI by building things that matter.</h2></div><div class="reveal"><p class="large">I’m a CSE (AI & ML) student at SRM TRP Engineering College, building a foundation in programming, AI concepts and real-world problem solving.</p><p class="muted">My current direction combines Generative AI, healthcare technology, smart-city systems and robotics-oriented ideas.</p><div class="facts"><div class="fact"><small>Degree</small><b>B.E. CSE (AI & ML)</b></div><div class="fact"><small>College</small><b>SRM TRP Engineering College</b></div><div class="fact"><small>Graduation</small><b>2029</b></div><div class="fact"><small>Current</small><b>2nd Year · 1st Sem</b></div></div></div></div></section>
<section class="section alt" id="skills"><div class="container"><div class="heading reveal"><span class="eyebrow">02 · Skills</span><h2>The toolkit I’m growing.</h2><p>Focused foundations rather than a long list of unverified technologies.</p></div><div class="skills">${skills.map((s,i)=>`<div class="skill reveal"><span class="eyebrow">0${i+1}</span><h3>${s[0]}</h3><div class="tags">${s[1].map(t=>`<span class="tag">${t}</span>`).join("")}</div></div>`).join("")}</div></div></section>
<section class="section" id="projects"><div class="container"><div class="heading reveal"><span class="eyebrow">03 · Featured Work</span><h2>Projects built around real problems.</h2><p>Four portfolio tracks showing the direction of my learning and development.</p></div><div class="projects">${projects.slice(0,3).map((p,i)=>card(p,i)).join("")}</div><div class="center"><a class="btn secondary" href="#all-projects">View all projects ↗</a></div></div></section>
<section class="section alt" id="journey"><div class="container"><div class="heading reveal"><span class="eyebrow">04 · Journey</span><h2>Hackathons, presentations & recognition.</h2><p>Technical participation that has helped me learn, communicate and build.</p></div><div class="timeline">${timeline.map(x=>`<div class="event reveal"><div class="date">${x[0]}</div><div class="line"><i></i></div><div class="event-card"><span class="eyebrow">${x[1]}</span><h3>${x[2]}</h3><p>${x[3]}</p></div></div>`).join("")}</div></div></section>
<section class="section" id="credentials"><div class="container"><div class="heading reveal"><span class="eyebrow">05 · Credentials</span><h2>Certifications, presentations & participation.</h2><p>Publicly display only the original credentials you are comfortable sharing.</p></div><div class="credentials">${credentials.map(c=>`<article class="credential reveal"><span class="eyebrow">${c[3].split(" ")[0]} · Credential</span><h3>${c[0]}</h3><p>${c[1]}</p><strong style="color:#59abff;font-size:11px">${c[2]}</strong><small>${c[3]}</small><span class="note" style="margin-top:15px">Add original certificate file in <code>assets/certificates/</code>.</span></article>`).join("")}</div></div></section>
<section class="contact"><div class="container contact-box"><div><span class="eyebrow">06 · Contact</span><h2>Let’s build, learn or compete.</h2><p>Project discussions, hackathons and technical collaboration.</p></div><div class="actions"><a class="btn primary" href="mailto:${P.email}">Email me ↗</a><a class="btn secondary" href="${P.leetcode}" target="_blank">LeetCode ↗</a></div></div></section>
</main>${footer()}`}
function allProjects(){return `${header()}<main class="page"><div class="container"><a class="back" href="#home">← Back home</a><span class="eyebrow">Project Archive</span><h1>Ideas → prototypes → learning.</h1><p class="page-intro">Explore the work shaping my path toward AI engineering.</p><div class="projects">${projects.map((p,i)=>card(p,i)).join("")}</div><div class="note"><b>Build in public, but stay accurate.</b> Concepts are labeled as concepts and working demos as demos.</div></div></main>${footer()}`}
function detail(slug){let p=projects.find(x=>x.slug===slug);if(!p)return allProjects();return `${header()}<main class="page"><div class="container"><a class="back" href="#all-projects">← All projects</a><div class="detail reveal"><div class="detail-icon">${p.icon}</div><span class="eyebrow">${p.area}</span><h1>${p.title}</h1><p class="page-intro">${p.desc}</p><div class="tags">${p.tags.map(t=>`<span class="tag">${t}</span>`).join("")}</div><div class="actions"><a class="btn primary" href="${p.repo}" target="_blank">Open GitHub ↗</a></div></div><div class="detail-grid"><div class="panel reveal"><span class="eyebrow">01 · Status</span><h2>Project state</h2><p>${p.status}</p></div><div class="panel reveal"><span class="eyebrow">02 · Core ideas</span><h2>Highlights</h2><ul class="check">${p.points.map(x=>`<li>${x}</li>`).join("")}</ul></div><div class="panel reveal"><span class="eyebrow">03 · Recognition</span><h2>Event / context</h2><p>${p.event}</p></div><div class="panel reveal"><span class="eyebrow">04 · Repository</span><h2>Code & documentation</h2><p>Use the linked GitHub project folder for source code, documentation and future iterations.</p><a class="link" href="${p.repo}" target="_blank">Open repository ↗</a></div></div></div></main>${footer()}`}
function reveal(){let o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("show")),{threshold:.12});document.querySelectorAll(".reveal").forEach(x=>o.observe(x))}
function render(){let h=location.hash||"#home";let html=h==="#all-projects"?allProjects():h.startsWith("#project/")?detail(h.split("/")[1]):home();$("#app").innerHTML=html;$("#menu")?.addEventListener("click",()=>$("#links").classList.toggle("open"));document.querySelectorAll(".links a").forEach(a=>a.addEventListener("click",()=>$("#links")?.classList.remove("open")));reveal();window.scrollTo(0,0)}
addEventListener("hashchange",render);render();